#experiment name
exp_name: test

#hyperparameters
hyperparams:
  lr: 0.001
  bs: 512
  iterations: 10000000
  epochs: 1
  num_workers: 8

#dataset
data:
  train:
    name: imgloader
    image_path: /home/bharathsk/projects/nerf/data/images/weic2216b.jpg
    size: 10000000
  val:
    name: testloader
    image_path: /home/bharathsk/projects/nerf/data/images/weic2216b.jpg
  test:
    name: testloader
    image_path: /home/bharathsk/projects/nerf/data/images/weic2216b.jpg

#embeddings
embeddings: 
  name: 'sinusoidal'
  num_freq: 10

#model definition
model:
  name: 'imgdigest'
  input_dim: 40
  hidden_dim: 256
  output_dim: 3
  num_hidden_layers: 8

#loss functions:
loss:
  name: 'mse'

#optimizer
optimizer:
  name: 'adam'

#metrics
metrics:
  list: ['mse', 'psnr', 'ssim']

#paths
paths:
  exp_dir: /home/bharathsk/projects/nerf/exps
  data_dir: /home/bharathsk/projects/nerf/data