#experiment name
exp_name: drop_1

#hyperparameters
hyperparams:
  lr: 0.001
  rays: 4096
  samples_coarse: 64
  samples_fine: 128
  iterations: 10000000
  epochs: 1
  num_workers: 8

#dataset
data:
  train:
    name: colmap
    image_path: /home/bharathsk/datasets/drop/frames/drop_2/
    sparse_recon_path: /home/bharathsk/datasets/drop/colmap/drop_2/sparse/0/
    size: 10000000
  val:
    name: colmap
    image_path: /home/bharathsk/datasets/drop/frames/drop_2/
    sparse_recon_path: /home/bharathsk/datasets/drop/colmap/drop_2/sparse/0/
    size: None
  test:
    name: colmap
    image_path: /home/bharathsk/datasets/drop/frames/drop_2/
    sparse_recon_path: /home/bharathsk/datasets/drop/colmap/drop_2/sparse/0/
    size: None
  analysis:
    name: colmap
    image_path: /home/bharathsk/datasets/drop/frames/drop_2/
    sparse_recon_path: /home/bharathsk/datasets/drop/colmap/drop_2/sparse/0/
    size: None

#embeddings
embeddings: 
  name: 'sinusoidal'
  num_freq_loc: 20
  num_freq_dir: 10

#model definition
model:
  name: 'nerf'
  hidden_dim: 256
  num_intermediate_layers: 6
  num_final_layers: 2

#loss functions:
loss:
  name: 'mse'

#optimizer
optimizer:
  name: 'adam'
  weight_decay: 0.000001

#metrics
metrics:
  list: ['mse', 'psnr', 'lpips', 'ssim']

#paths
paths:
  exp_dir: /home/bharathsk/projects/nerf/exps
  data_dir: /home/bharathsk/projects/nerf/data
  resume: /home/bharathsk/projects/nerf/exps/lr_5e-3_bs_4096/nerf/image/67990ff3dba3433bbec1033fc45f1141/checkpoints/epoch=0-step=1221.ckpt