#experiment name
exp:
  root: /home/bharathsk/projects/nerf/exps/
  name: dict_all
  offline_logging: False

#hyperparameters
hyperparams:
  lr: 0.0005
  num_rays: 9000
  test_num_rays: 9000
  num_samples_coarse: 64
  num_samples_fine: 128
  iterations: 10000000
  epochs: 6
  num_workers: 24

#dataset
data:
  downscale: 2
  train:
    name: colmap
    image_path: /home/bharathsk/datasets/drop/frames/drop_2/
    sparse_recon_path: /home/bharathsk/datasets/drop/colmap/drop_2/sparse/0/
    imgs_list: NULL
    size: 10000000
  val:
    name: colmap
    image_path: /home/bharathsk/datasets/drop/frames/drop_2/
    sparse_recon_path: /home/bharathsk/datasets/drop/colmap/drop_2/sparse/0/
    imgs_list: [30]
    size: NULL
  test:
    name: colmap
    image_path: /home/bharathsk/datasets/drop/frames/drop_2/
    sparse_recon_path: /home/bharathsk/datasets/drop/colmap/drop_2/sparse/0/
    imgs_list: [30]
    size: NULL
  analysis:
    name: colmap
    image_path: /home/bharathsk/datasets/drop/frames/drop_2/
    sparse_recon_path: /home/bharathsk/datasets/drop/colmap/drop_2/sparse/0/
    imgs_list: [30]
    size: NULL

#embeddings
embeddings: 
  name: 'sinusoidal'
  num_freq_loc: 10
  num_freq_dir: 4

#model definition
model:
  name: 'nerf'
  hidden_dim: 256
  num_intermediate_layers: 6
  num_final_layers: 2

#loss functions:
loss:
  names: ['mse']
  weights: [1.0]

#optimizer
optimizer:
  name: 'adam'
  weight_decay: 0.0000001

#metrics
metrics:
  list: ['mse', 'psnr', 'lpips', 'ssim']